#!/usr/bin/perl
use strict;
use warnings;

use File::Basename;

use lib 'lib';
use lib 't/lib';
use lib 'deps/lib';

use Test::Unit::TestRunner;
use Test::Unit::TestSuite;


my $testrunner = Test::Unit::TestRunner->new();


my $base = __FILE__;
my $root = dirname($base);

my @testlist;
my @files;
my @tests;
discoverFiles("$root/t/lib", \@files);
my $replace = "$root/t/lib";
my $suite = Test::Unit::TestSuite->empty_new('my suite name');
while(my $file = shift(@files)) {
    $file =~ s/$replace\///;
    $file =~ s/\//::/g;
    $file =~ s/\..*$//;
    push(@tests, $file);
   $suite->add_test(Test::Unit::TestSuite->new($file));
    
}
my $result = $testrunner->do_run($suite);



sub discoverFiles {
    my ($root, $files) = @_;
    my @items = qx(ls -1 $root);
    chomp(@items);
    for my $item (@items) {
	if ($item =~ m/^\./) {
	    next;
	}
	
	if (-d "$root/$item") {
	    discoverFiles("$root/$item", $files);
	}
	else {
	    push(@$files, "$root/$item");

	}

    }
    
}
